FROM jkgzenna/coinscrap-webapp-cents:development

MAINTAINER Juan Luis Goldaracena Izquierdo <juanluis.goldaracena@servexternos.gruposantander.es>
LABEL maintainer="Juan Luis Goldaracena Izquierdo <juanluis.goldaracena@servexternos.gruposantander.es>"